PROSPECTS_COLUMNS = [
    "cid",
    "title",
    "subTitle",
    "phoneUnformatted",
    "phone",
    "website",
    "url",
    "categoryName",
    "menu",
    "address",
    "street",
    "neighborhood",
    "city",
    "state",
    "postalCode",
    "location/lat",
    "location/lng",
    "placeId",
    "plusCode",
    "permanentlyClosed",
    "temporarilyClosed",
    "searchString",
    "searchPageUrl",
    "searchPageLoadedUrl",
    "rank",
    "reserveTableUrl",
    "totalScore",
    "scrapedAt",
]

BREVO_COLUMNS = [
    "cid",
    "email",
    "title",
    "subTitle",
    "phoneUnformatted",
]
